### ISSUE TITLE
 [Website]:  New page for survey data

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#504]
### Tasks 

- [x] New page (.../surveys/responses) with title `Survey responses`
- [x] Basic layout for showing all questions and answer per survey type ([Figma](https://www.figma.com/proto/qGO3YI21AWIjWEyMPGUczM/Social-Income-Main-(Web%2C-App)?node-id=4059-9320&t=Vuwyom3DeJyxfzYq-1))
- [ ] Retrieve survey data, make basic calculations (%, count etc.) and show in a raw file all data (see also `...transparency/finances/raw-payment-stats`)
- [ ] Add the designed elements on the new page like in [Figma](https://www.figma.com/proto/qGO3YI21AWIjWEyMPGUczM/Social-Income-Main-(Web%2C-App)?node-id=4059-9320&t=Vuwyom3DeJyxfzYq-1) using components like [chart](https://ui.shadcn.com/docs/components/chart), [badge](https://ui.shadcn.com/docs/components/badge), [card](https://ui.shadcn.com/docs/components/card) etc.

**Maybe worth thinking about early on:**
Considering how to make the structure scalable for additional countries, we could incorporate [countries] into the folder structure, similar to [currencies] in transparency/finances. This would allow for URLs like ...surveys/responses/sl (with sl representing Sierra Leone), setting up a flexible framework that enables displaying surveys by country in the future.

**Out of scope**
- generate specific insights with survey data (this can be done in a second step and has to be added in the designs first)
- filterning answers by variables (gender, age etc.)

### Design Draft ([Figma](https://www.figma.com/proto/qGO3YI21AWIjWEyMPGUczM/Social-Income-Main-(Web%2C-App)?node-id=4059-9320&t=Vuwyom3DeJyxfzYq-1))

![Image](https://github.com/user-attachments/assets/b293cb67-644c-4f53-b290-db934aab0e1b)

**Observed (maybe a quick fix)**
- The data is loaded when survey is opened [via recipient collection](https://staging-admin.socialincome.org/c/recipients/3RqjohcNgUXaejFC7av8/surveys/checkin-1), but not when opened directly in [survey view](https://staging-admin.socialincome.org/c/surveys/checkin-1)

![Image](https://github.com/socialincome-san/public/assets/6095849/4f656834-07c0-40a8-85d8-0518dd81b60b)

**Comment by Gavriil-Tzortzakis** [comment]
Hi , do you still need help here? I am interested.

**Comment by ssandino** [comment]
> Hi , do you still need help here? I am interested.

Are you based in Zurich? We'll meet this Thursday evening if you would like to join for a drink and discuss.

**Comment by Gavriil-Tzortzakis** [comment]
Hi Sandino, I do live in Zurich and will be happy to join. I finish work around 17:30-18:00 . Please send me the meeting place/details at my email gavriiltzortzakis@gmail.com.   

Cheers,
Gavriil

**Comment by ssandino** [comment]
done @Gavriil-Tzortzakis - see you later today!
