### ISSUE TITLE
[Website Feature]: Landing page with new design

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#750]
### Is there an existing request for this feature?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

Implementation of the [Figma designs](https://www.figma.com/file/qGO3YI21AWIjWEyMPGUczM?node-id=1653:6882&locale=en&type=design) from Milk with the structure and approach discussed with @mkue on Feb 22.

### Describe the solution/feature

---

### Perfecting sections

- [x] Hero Video section
- [in progress] Overview section
- [in progress] Monthly Income section
- [x] Explainer video section
- [x] Mobile Illustration section
- [x] FAQ section
- [x] Approach section
- [x] Quotes section
- [x] Recipient Selections section
- [x] Testimonials section
- [x] Sdgoals section
- [ ] Journal section

---

### Subtasks

- [x] Hero Video section
- [x] Brief Overview section
- [x] Monthly income section ~~(to skip for now)~~
- [x] Explainer Video section (to skip for now)
- [x] Mobile Illustration section (to skip for now)
- [x] FAQ Accordion section
- [x] Approach section
- [x] Quotes Carousel-1 section
- [x] Unique recipients section
- [x] Testimonials Cards Carousel (-2) section
- [x] Sdgoals Tilted cards section
- [x] Journal section
- [x] Footer
- [ ] Navbar (to skip for now)

### Anything else?

Out of scope:

- Navigation
- Donation process
- Movie player

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community

**Comment by ssandino** [comment]
Connected to #895
