### ISSUE TITLE
[Website]: GitHub insights on website

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#881]
### Is there an existing request for this feature?

- [ ] I have searched the existing issues

### Describe the solution/feature

**This issue is part of the GitHub DPG Community Manager Program:**

Goal: To better highlight our OSS contributors and lower the barriers to entry for new contributors, we plan to create a simple webpage that utilizes GitHub's API. This page will display in _Phase 1_ all contributors and count of their commits (like shown [here](https://github.com/socialincome-san/public/graphs/contributors)). It will be a scaled-down version, serving as a foundation for future features that expand on this basic information.

![Image](https://github.com/user-attachments/assets/571c9f9f-1d54-4812-a5d8-9418ba528b66)

The stats and information should be fetched through the GitHub API (Phase 1: not authenticated requests)

You can use components from the library Shadcn. Most likely a [card](https://ui.shadcn.com/docs/components/card) without card header and footer to show the profile image and name would do the job. No specific styling is needed for this issue, as it will be addressed separately.

### **Phase 1** 

**Step 1: Setup Environment**

- [x] Set up the local environment as outlined in the [Readme](https://github.com/socialincome-san/public/blob/main/README.md).
- [x] Confirm that `npm run website:serve` runs successfully.

If you have questions, ask in the Slack common conversation with @elizabeth-agada and @ssandino.

**Upon completion:** Call with @elizabeth-agada and @ssandino.

**Step 2: Create a Working Prototype**

- [x] Create a /open-source page and an EN translation file with text elements.
- [x] Commit a draft PR.
- [x] Add code to retrieve contributors’ info from our GitHub repo (see [reference](https://dev.to/hadithtech/5-different-ways-to-get-contributors-through-the-github-api-4gc)), disregarding [rate limits](https://docs.github.com/en/rest/using-the-rest-api/rate-limits-for-the-rest-api?apiVersion=2022-11-28) for unauthenticated requests.

**Upon completion:** Get the first code review and we make a call to discuss the phase 2 (authentication for higher rates, other data to show etc.).

### **Phase 2** 

  1. [x] See with @mkue how to best use token to have authorized access. Answer: Personal Access Token (PAT) stored as Vercel secret. This should address both issues: increasing the rate limit overall and resolving the Vercel preview link limit.
  2. [ ] Implement new authentication method and test (locally, preview link)
  3. [ ] Adding additional information as shown in this [Figma design](https://www.figma.com/design/qGO3YI21AWIjWEyMPGUczM/Social-Income-Main-(Web%2C-App)?node-id=4205-3003&t=GICWytExzOfy6xkj-1). Make different sections and use the shadcn components [cards](https://ui.shadcn.com/docs/components/card) (good [template](https://ui.shadcn.com/examples/dashboard)) and [table](https://ui.shadcn.com/docs/components/table) (good [template](https://ui.shadcn.com/examples/tasks)).

![Image](https://github.com/user-attachments/assets/fccf27d0-e2dc-4a18-8e06-c58198fc9d53)

### Code of Conduct

- [X] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community
