### ISSUE TITLE
[Web]: Optimization of campaign pages

### ISSUE THREAD

**Issue by ssandino** [socialincome-san/public#931]
### Is there an existing request for this feature?

- [x] I have searched the existing issues

### How does this feature help us achieve our primary goal of reaching the maximum number of people in need?

Optimized campaign pages drive higher funding, especially through recurring donations, enabling us to support even more individuals in need.

```[tasklist]
### Tasks
- [ ] Profile image: Adding the option to upload a image through the admin tool, that is presented as avatar in different places on the campaign page to make it more personal
- [ ] Newsletter signup: Adding direct newsletter signup for users on the campaign page which signs them up for normal newsletter (without welcoming emails) and for an alert, when campaign, where they signup 
- [ ] Links below info texts: Adding option to have links in the informational text boxes
- [ ] Optimize donation card: To make it more appealing to donate and specially attract recurring donations
- [ ] Optimize progress bar: To better highlight important information
``` 
Details about tasks see below.

### Describe the solution/feature

**Profile image**
- This should make the campaigns more personal
- The upload can be through the admin tool (firecms has an [upload function](https://firecms.co/docs/2.0.0/properties/fields/file_upload))
- The profile image can use the [avatar component of shadcn](https://ui.shadcn.com/docs/components/avatar)
- If no profile image is uploaded, it just ignores the div
![Image](https://github.com/user-attachments/assets/7178eea7-442d-4f2d-8fcd-79cd74c2dbed)

**Newsletter signup** 
- This should sign them up for the standard newsletter (like [here](https://socialincome.org/en/int/newsletter)), this without the welcome emails
- This should sign them up for future alerts on the campaign (like "campaign reached 90% help it to reach the goal")
- This feature should be added as an option (boolean) in the admin, cause there might be campaigns where this doesn't make sense (for example thematic fundraisers with no end etc.)
![Image](https://github.com/user-attachments/assets/0caee84a-0ef1-4f0e-825b-146e53efad37)

**Links below info texts**
- This is used to point to additional information, for examples social media accounts of the campaign owners
![Image](https://github.com/user-attachments/assets/64d4f941-6fdb-4141-abb0-72b25b7919b4)

**Optimize donation card**
- Monthly donations now the default (and added ❤️ symbol)
- Selected options are now all blue (not yellow) and small aligning adjustments
- The field to enter custom amount only appears when clicking on "others"
- Donation amount should be mentioned in the button text for better information
- If someone makes a one-time donation, propose a cheaper recurring donation as last step (like [Mozilla Foundation](https://foundation.mozilla.org/en/))

![Image](https://github.com/user-attachments/assets/951138a4-8312-4123-94a1-bbffab06a23d)
![Image](https://github.com/user-attachments/assets/e0b0309f-7f9a-4c98-8838-cbfcf2b4c64d)
![Image](https://github.com/user-attachments/assets/996b8b82-8413-4358-85cb-f3d36039d9c5)

**Optimize progress bar**
- highlight amount of contributors in a badge to better show collective effort
- Get rid of the .00 in the numbers and small text size changes

![Image](https://github.com/user-attachments/assets/610b3cb7-6b1a-4ee1-8cfe-aa4e3ee499c1)

### Anything else?

The Figma designs are [here](https://www.figma.com/design/qGO3YI21AWIjWEyMPGUczM/Social-Income-Main-(Web%2C-App)?node-id=1653-6882&t=UDBmUEHyHGCxeTPF-1)

### Code of Conduct

- [x] I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community
